Draggable Reorder
sanctuarycomputer/contentful-fragment pull request #13
Opened 2018-11-05 17:35 UTC by aliciakw

Create grid and list-item wrapper components using the Muuri library to allow users to change the order of fragment cards by clicking and dragging.

You can verify that the order is persisted by looking at the JSON preview.

2018-11-05 19:35 UTC, joshiefishbein commented on app/templates/index.old.hbs
> +{{#if extension.data._schema}}
We still need this file?

2018-11-05 20:19 UTC, aliciakw commented on app/templates/index.old.hbs
> +{{#if extension.data._schema}}
nope nope`

2018-11-05 21:04 UTC, joshiefishbein approved these changes

2018-11-05 21:12 UTC, hhff commented
This is awesome

Do you think we could set it up to visually behave like the reorderable interaction on contentful proper?

- [ ] Has a draggable handle (which has a darkened hover effect)
- [ ] Hovers up slightly when hovered anywhere

![image](https://user-images.githubusercontent.com/2865404/48026942-7814ec00-e115-11e8-8d39-cb9f96f6526c.png)

2018-11-05 21:13 UTC, hhff requested changes

2018-11-05 21:13 UTC, hhff commented on app/components/muuri-grid-component.js
> +  didRender() {
This this work on `didInsertElement`?

`didRender` is called multiple times:
https://guides.emberjs.com/release/components/the-component-lifecycle/#toc_making-updates-to-the-rendered-dom-with-didrender

2018-11-05 21:16 UTC, hhff commented on app/components/muuri-grid-component.js
> +  didRender() {
We should probably tear this binding down too on willRemoveElement hook

2018-11-15 19:14 UTC, limsohee1002 approved these changes

2019-01-08 21:21 UTC, aliciakw commented
<img width="400" alt="screen shot 2019-01-08 at 4 20 32 pm" src="https://user-images.githubusercontent.com/7025087/50859446-60e6ba80-1361-11e9-9aca-c283a9434b6c.png">

Updated to look like Contentful @hhff !  @joshiefishbein says Ample is asking for this feature so lmk if it looks good to merge.

2019-01-08 21:36 UTC, merged