Fix initial load for free schema + TESTS
sanctuarycomputer/contentful-fragment pull request #15
Opened 2018-11-09 23:15 UTC by aliciakw

2018-11-10 00:56 UTC, hhff approved these changes
LGTM outside of extra file. Let's setup CircleCI on Monday!

2018-11-10 00:56 UTC, hhff commented on tests/unit/services/file.js
> +};
Is this file necessary?

2018-11-10 17:31 UTC, aliciakw commented on tests/unit/services/file.js
> +};
oh whoops was testing something

2018-11-13 15:13 UTC, limsohee1002 approved these changes

2018-11-13 16:35 UTC, hhff requested changes

2018-11-13 16:35 UTC, hhff commented on .circleci/config.yml
> +  working_directory: ~/contentful-fragment
u can snip this

2018-11-13 16:35 UTC, hhff commented on .circleci/config.yml
> +        at: ~/contentful-fragment
and this!

2018-11-13 16:35 UTC, hhff commented on .circleci/config.yml
> +        paths: .
and this

2018-11-13 16:35 UTC, hhff commented on .circleci/config.yml
> +        at: ~/contentful-fragment
and dis

2018-11-13 16:35 UTC, hhff commented on .circleci/config.yml
> +        - v1-dependencies-
u can lose this cause we shouldn't have a non-specific cache key

2018-11-13 20:54 UTC, joshiefishbein approved these changes

2018-11-13 21:31 UTC, merged